import '../src/index.css';
import { Toaster } from 'react-hot-toast';
import Providers from './Providers';

export const metadata = {
  title: 'Dheeran Crackers',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Toaster position="top-right" toastOptions={{ duration: 3000 }} />
          {children}
        </Providers>
      </body>
    </html>
  );
}
